#!/usr/bin/env python3
"""EAGLES SessionStart hook — surface capabilities + recent learned patterns.

Outputs to stdout (appended to session context). Fails OPEN on any error.
Latency budget: <200ms.

Surfaces:
  1. Top skills from .data/skill-catalog.json (generated by dump-skill-catalog.mjs)
  2. Top 5 recent learned patterns from learning.sqlite
  3. Enforcement notice (hard-block at 4 mutations without task_create)

See ADR-008-SESSION-START-CONTRACT.md for rationale.
"""
import json
import os
import sqlite3
import sys
from pathlib import Path

DATA_ROOT = Path(os.environ.get(
    "EAGLES_DATA_ROOT",
    r"C:\RH-OptimERP\eagles-ai-platform\.data"
))


def load_top_skills(limit=10):
    """Load top skills from the JSON-dumped catalog."""
    catalog_path = DATA_ROOT / "skill-catalog.json"
    if not catalog_path.exists():
        return []
    try:
        with catalog_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        skills = data.get("skills", [])
        # Take first N — they're in the order defined by the TypeScript catalog
        return skills[:limit]
    except Exception:
        return []


def load_recent_patterns(limit=5):
    """Load recent patterns from learning.sqlite.

    Uses the ACTUAL schema: learning_patterns table with columns
    pattern_id, name, description, success_rate, total_attempts, tags, archived.
    """
    db = DATA_ROOT / "learning.sqlite"
    if not db.exists():
        return []
    try:
        conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True, timeout=0.5)
        rows = conn.execute(
            "SELECT pattern_id, name, description, success_rate, total_attempts "
            "FROM learning_patterns "
            "WHERE archived = 0 AND success_rate >= 0.5 "
            "ORDER BY updated_at DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return rows
    except Exception:
        return []


def main():
    skills = load_top_skills()
    patterns = load_recent_patterns()

    lines = [
        "# EAGLES Session Contract",
        "",
        "**6 MCP servers loaded.** For multi-step tasks, call "
        "`mcp__orchestrator__task_create` FIRST (or `task_build_decomposition_prompt`).",
        "",
    ]

    if skills:
        skill_names = ", ".join(s["name"] for s in skills[:10])
        lines.append(f"**Top {len(skills)} skills**: {skill_names}")
    else:
        lines.append("**Skills**: catalog not available (run `node scripts/dump-skill-catalog.mjs`)")
    lines.append("")

    if patterns:
        lines.append(f"**Recent learned patterns ({len(patterns)}):**")
        for pid, name, desc, rate, attempts in patterns:
            desc_short = (desc or "")[:100]
            lines.append(
                f"- [{name}] success_rate={rate:.2f} ({attempts} attempts): {desc_short}"
            )
    else:
        lines.append("**Patterns**: learning_patterns empty (SonaLearning will populate)")
    lines.append("")

    lines.append(
        "**Enforcement**: after 4 Edit/Write calls without `task_create`, "
        "mutations will be BLOCKED (exit 2)."
    )
    lines.append("**Escape hatch**: set `EAGLES_BYPASS=1` in env to override.")
    lines.append("")

    print("\n".join(lines))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        # Fail OPEN — never block session start
        print(f"[eagles-session-start] warn: {e}", file=sys.stderr)
        sys.exit(0)
