/**
 * Style Dictionary v4 configuration — 3 output platforms:
 * 1. dist/tokens.css      — CSS custom properties with :root + [data-theme="dark"] blocks
 * 2. dist/tokens.js       — ESM typed token object
 * 3. dist/tailwind-tokens.js — Tailwind preset (theme.extend values)
 *
 * Dark mode: tokens declare overrides via `$extensions.modes.dark` in the
 * W3C source. The custom `css/variables-with-modes` format below walks the
 * dictionary, emits the light :root block, then emits a second block under
 * `[data-theme="dark"]` with only the overridden names.
 */
import StyleDictionary from 'style-dictionary';

// -----------------------------------------------------------------------------
// Custom format: css/variables-with-modes
// -----------------------------------------------------------------------------
// Pulls the dark-mode override (if any) from token.$extensions.modes.dark or
// the parsed original.extensions.modes.dark (SD v4 flattens `$extensions` into
// `extensions` on the transformed token).
function extractDarkValue(token: any): string | null {
  const ext =
    token?.$extensions?.modes?.dark ??
    token?.extensions?.modes?.dark ??
    token?.original?.$extensions?.modes?.dark ??
    token?.original?.extensions?.modes?.dark;

  return typeof ext === 'string' ? ext : null;
}

// SD references like "{base.violet.400}" must be resolved against the same
// dictionary the main build uses. We keep it simple: if the override contains
// a reference, we leave it in place so SD's own reference resolution can run
// during the dark pass — but since we emit raw CSS here, we expand manually.
function resolveReference(
  raw: string,
  dictionaryTokens: Record<string, any>,
): string {
  const match = raw.match(/^\{([^}]+)\}$/);
  if (!match) return raw;

  const path = match[1].split('.');
  let node: any = dictionaryTokens;
  for (const segment of path) {
    if (node == null) return raw;
    node = node[segment];
  }

  if (node && typeof node === 'object' && '$value' in node) {
    return String(node.$value);
  }
  return raw;
}

StyleDictionary.registerFormat({
  name: 'css/variables-with-modes',
  format: ({ dictionary, file }) => {
    const tokens = dictionary.allTokens;

    const lightLines: string[] = [];
    const darkLines: string[] = [];

    for (const token of tokens) {
      const name = `--${token.name}`;
      const lightValue = String(token.value);
      lightLines.push(`  ${name}: ${lightValue};`);

      const darkRaw = extractDarkValue(token);
      if (darkRaw != null) {
        const darkResolved = resolveReference(darkRaw, dictionary.tokens);
        darkLines.push(`  ${name}: ${darkResolved};`);
      }
    }

    const header = `/**\n * ${file?.destination ?? 'tokens.css'} — auto-generated by Style Dictionary.\n * Do not edit directly.\n *\n * Light theme is the default (:root). Dark theme is opt-in via\n * \`<html data-theme="dark">\` and overrides only the system-layer tokens\n * that diverge. Component and base tokens are identical across modes.\n */\n`;

    const root = `:root {\n${lightLines.join('\n')}\n}\n`;
    const dark = darkLines.length
      ? `\n[data-theme="dark"] {\n${darkLines.join('\n')}\n}\n`
      : '';

    return `${header}\n${root}${dark}`;
  },
});

// -----------------------------------------------------------------------------
// Config
// -----------------------------------------------------------------------------
export default {
  source: ['tokens/tokens.w3c.json'],
  log: { verbosity: 'verbose' },

  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-with-modes',
          options: {
            outputReferences: false,
          },
        },
      ],
    },

    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },

    tailwind: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tailwind-tokens.js',
          format: 'javascript/es6',
          options: {
            outputReferences: false,
          },
        },
      ],
    },
  },
};
